[theme]
base = "light"
primaryColor = "#111111"
backgroundColor = "#FBFBFA"
secondaryBackgroundColor = "#F7F6F3"
textColor = "#2F3437"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "watchdog"
runOnSave = true

[browser]
gatherUsageStats = false
